import assert from 'node:assert/strict';
import {buildAssessmentContext,mapChangeStatus} from '../ai/assessment-context.mjs';
const data={updated_at:'2026-10-02T12:50:17.456Z',risk_signals:[{id:'a',description:'Flood warning',risk_domain:'flooding',risk_theme:'natural_and_environmental_hazards',hazard:'river flooding',geography:{scope:'England'},severity:'high',status:'active',change_type:'new',source:'Source A',source_url:'source',confidence:'high',priority_band:'high'},{id:'b',description:'Weather signal',risk_domain:'climate_and_weather',risk_theme:'natural_and_environmental_hazards',hazard:'heavy rain',geography:{scope:'Wales'},severity:'moderate',status:'monitoring',change_type:'updated',source:'Source B',source_url:'source',confidence:'high',priority_band:'moderate'},{id:'c',description:'International signal',risk_domain:'cyber',risk_theme:'cyber',hazard:'vulnerability',geography:{scope:'international'},severity:'unknown',status:'active',change_type:'new',source:'Source C',source_url:'source',confidence:'high',priority_band:'monitor'}],feeds:{old:{ok:true,stale:true},broken:{ok:false,stale:true}}};
const c=buildAssessmentContext(data,{geography:'UK',themes:['natural_and_environmental_hazards'],minimum_priority:'monitor'});
assert.equal(c.assessment_id,'LS-20261002T125017Z');assert.equal(c.signals.length,2);assert.deepEqual(c.signals.map(s=>s.signal_id),['a','b']);assert.equal(c.signals[0].change_status,'new');assert.equal(c.signals[1].change_status,'changed');assert.equal(c.relationships.length,0);assert.deepEqual(c.data_quality.stale_sources,['old','broken']);assert.deepEqual(c.data_quality.failed_sources,['broken']);assert.equal(mapChangeStatus('resolved'),'resolved');assert.equal(mapChangeStatus('escalated'),'changed');const high=buildAssessmentContext(data,{geography:'England',themes:[],minimum_priority:'high'});assert.equal(high.signals.length,1);console.log('MVP5 assessment-context builder checks: PASS');

// #47 authoritative source provenance
const provenanceData={updated_at:'2026-10-02T12:50:17.456Z',risk_signals:[{id:'flood-1',description:'Rivers Ehen, Calder, Irt and Esk',risk_domain:'flooding',hazard:'river flooding',geography:{scope:'England'},severity:'moderate',status:'active',change_type:'new',source:'Environment Agency',source_url:'https://check-for-flooding.service.gov.uk/',source_record_id:'ea:flood-1',source_native_status:'Flooding is possible – be prepared',confidence:'high',priority_band:'high'}],feeds:{}};
const registry={sources:[{publisher:'Environment Agency',landing_url:'https://check-for-flooding.service.gov.uk/',guidance_references:[{title:'Prepare for flooding',url:'https://www.gov.uk/prepare-for-flooding'},{title:'What to do before or during a flood',url:'https://www.gov.uk/help-during-flood'}]}]};
const p=buildAssessmentContext(provenanceData,{geography:'England',source_registry:registry}).signals[0];
assert.equal(p.authoritative_source_url,'https://check-for-flooding.service.gov.uk/');assert.equal(p.source_record_id,'ea:flood-1');assert.equal(p.source_native_status,'Flooding is possible – be prepared');assert.equal(p.guidance_references.length,2);assert.equal(p.guidance_references[0].title,'Prepare for flooding');assert.equal(p.severity,'moderate');
const missing=buildAssessmentContext({...provenanceData,risk_signals:[{...provenanceData.risk_signals[0],source_native_status:undefined}]},{geography:'England'}).signals[0];assert.equal(missing.source_native_status,null);assert.deepEqual(missing.guidance_references,[]);
