const UK_GEOGRAPHIES = new Set(['UK', 'England', 'Wales', 'Scotland', 'Northern Ireland']);
const PRIORITY_RANK = { monitor: 1, moderate: 2, high: 3, immediate: 4 };
function matchesGeography(s,g){if(!g||g==='all')return true;const x=s?.geography?.scope;if(g==='UK')return UK_GEOGRAPHIES.has(x);return x===g;}
function matchesThemes(s,t){return !Array.isArray(t)||t.length===0||t.includes(s.risk_theme);}
function matchesPriority(s,p='monitor'){return (PRIORITY_RANK[s.priority_band]??1)>=(PRIORITY_RANK[p]??1);}
function mapChangeStatus(x){if(x==='new')return'new';if(['updated','changed','escalated','de-escalated','resolved'].includes(x))return x==='resolved'?'resolved':'changed';return'unknown';}
function buildRelationships(signals){const out=[];for(let i=0;i<signals.length;i++)for(let j=i+1;j<signals.length;j++){const a=signals[i],b=signals[j],f=[];if(a.geography?.scope&&a.geography.scope===b.geography?.scope)f.push('shared geography');if(a.hazard&&a.hazard===b.hazard)f.push('shared hazard');if(a.domain&&a.domain===b.domain)f.push('shared domain');if(f.length)out.push({signal_ids:[a.signal_id,b.signal_id],relationship_type:'candidate_shared_context',supporting_evidence:['Signals share '+f.join(', ')+'; candidate relationship, not causation.']});}return out;}
function landscapeSnapshotId(timestamp){const iso=new Date(timestamp).toISOString();return 'LS-'+iso.slice(0,19).replace(/[-:]/g,'')+'Z';}
export function buildAssessmentContext(data,scope={}){if(!data||typeof data!=='object')throw new TypeError('RM data is required');const geography=scope.geography??'UK',themes=scope.themes??[],minimumPriority=scope.minimum_priority??'monitor';const raw=Array.isArray(data.risk_signals)?data.risk_signals:[];const signals=raw.filter(s=>matchesGeography(s,geography)).filter(s=>matchesThemes(s,themes)).filter(s=>matchesPriority(s,minimumPriority)).map(s=>({signal_id:s.id,title:s.description||s.source||'Risk signal',description:s.description||'',domain:s.risk_domain||'unknown',hazard:s.hazard||'unknown',geography:s.geography||{scope:'unknown'},severity:s.severity||'unknown',status:s.status||'unknown',published_at:s.published_at??null,updated_at:s.updated_at??null,change_status:mapChangeStatus(s.change_type),source:s.source||'Unknown source',authoritative_source:Boolean(s.source_url),evidence_confidence:s.confidence||'unknown'}));const stale=[],failed=[];for(const[n,h]of Object.entries(data.feeds||{})){if(h?.stale)stale.push(n);if(h?.ok===false)failed.push(n);}return{assessment_id:landscapeSnapshotId(data.updated_at||Date.now()),timestamp:data.updated_at||new Date().toISOString(),monitoring_scope:{geography,domains:[...new Set(signals.map(s=>s.domain))],filters:{themes:[...themes],minimum_priority:minimumPriority}},signals,relationships:buildRelationships(signals),data_quality:{stale_sources:stale,failed_sources:failed,limitations:raw.length?[]:['No risk signals were available in the RM snapshot.']}};}
export {mapChangeStatus};
